### ISSUE TITLE
Docs don't build using sphinx version in reqirements 

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2-docs#95]
At least not in Python 3.10. See https://github.com/sphinx-doc/sphinx/issues/9562

Can fix by enforcing newer Sphinx version. E.g. 5.x

**Comment by ptheywood** [comment]
Breathe added support for Sphinx 5.0 in the latest release (4.34.0, 2022-06-20). 

None of the breaking sphinx 5.0 changes look like they should impact us at a glance. 

Exhale >= 0.3.2 requires pyhton >= 3.7 (i.e. dropping 3.6), but otherwise doesn't seem to require specific breathe / sphinx versions / conflicts (atleast based on its change log). 

Moving to Sphinx >= 5.0 and Breateh >= 4.34 plus updating CI to use python 3.7 and 3.11 seems like it should be fine and will pull in a number of fixes.

**Comment by mondus** [comment]
I have tested on Sphinx 5.0 and all seems fine.

**Comment by mondus** [comment]
This should actually be Breathe >= 4.31 but bumping to 4.34 is no issue.
